### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#49] opened 2016-08-14 18:16 UTC
protocol.version: 1
os.name: Linux
java.version: 1.8.0_92
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-143.2370
app.version.major: 15
app.version.minor: 0.6
app.build.date: 1461790800000
app.build.date.release: 1446415200000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.03
last.action: StepOver
previous.exception: null
assignee.id: null

```
java.lang.AssertionError
    at org.jf.smalidea.debugging.value.LazyValue.getValue(LazyValue.java:128)
    at org.jf.smalidea.debugging.value.LazyObjectReference.enableCollection(LazyObjectReference.java:75)
    at com.intellij.debugger.impl.DebuggerUtilsEx.enableCollection(DebuggerUtilsEx.java:919)
    at com.intellij.debugger.engine.SuspendContextImpl.resume(SuspendContextImpl.java:95)
    at com.intellij.debugger.engine.SuspendManagerImpl.resume(SuspendManagerImpl.java:190)
    at com.intellij.debugger.engine.DebugProcessImpl$ResumeCommand.resumeAction(DebugProcessImpl.java:1728)
    at com.intellij.debugger.engine.DebugProcessImpl$StepCommand.resumeAction(DebugProcessImpl.java:1701)
    at com.intellij.debugger.engine.DebugProcessImpl$ResumeCommand.contextAction(DebugProcessImpl.java:1723)
    at com.intellij.debugger.engine.DebugProcessImpl$StepOverCommand.contextAction(DebugProcessImpl.java:1629)
    at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:61)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:153)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.a(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

```

```
null
```

**Comment by JesusFreke** [comment] 2016-10-23 18:15
Duplicate of #4

**Closed as completed by JesusFreke** 2016-10-23 18:15 UTC
