### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#62] opened 2016-08-31 05:32 UTC
protocol.version: 1
os.name: Linux
java.version: 1.8.0_76-release
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IC-162.1121.32
app.version.major: 2016
app.version.minor: 2
app.build.date: 1467993600000
app.build.date.release: 1467993600000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 141.3056
plugin.name: Smalidea
plugin.version: 0.03
last.action: null
previous.exception: null
assignee.id: null

```
java.lang.NoSuchMethodError: org.jf.smalidea.psi.impl.SmaliMethod.getStubOrPsiParent()Lcom/intellij/psi/PsiElement;
    at org.jf.smalidea.psi.impl.SmaliMethod.getContainingClass(SmaliMethod.java:262)
    at org.jf.smalidea.psi.impl.SmaliMethod.getContainingClass(SmaliMethod.java:66)
    at com.intellij.psi.util.PsiUtil.canBeOverriden(PsiUtil.java:947)
    at com.intellij.codeInsight.InferredAnnotationsManagerImpl.ignoreInference(InferredAnnotationsManagerImpl.java:82)
    at com.intellij.codeInsight.InferredAnnotationsManagerImpl.findInferredAnnotation(InferredAnnotationsManagerImpl.java:51)
    at com.intellij.codeInsight.AnnotationUtil$2$1.create(AnnotationUtil.java:166)
    at com.intellij.codeInsight.AnnotationUtil$2$1.create(AnnotationUtil.java:152)
    at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:56)
    at com.intellij.codeInsight.AnnotationUtil.findNonCodeAnnotation(AnnotationUtil.java:178)
    at com.intellij.codeInsight.AnnotationUtil.findAnnotation(AnnotationUtil.java:115)
    at com.intellij.codeInsight.AnnotationUtil.findAnnotation(AnnotationUtil.java:94)
    at com.intellij.codeInsight.AnnotationUtil.findAnnotation(AnnotationUtil.java:87)
    at com.intellij.codeInspection.JavaSuppressionUtil.getInspectionIdsSuppressedInAnnotation(JavaSuppressionUtil.java:85)
    at com.intellij.codeInspection.JavaSuppressionUtil.getInspectionIdsSuppressedInAnnotation(JavaSuppressionUtil.java:170)
    at com.intellij.codeInspection.JavaSuppressionUtil.getSuppressedInspectionIdsIn(JavaSuppressionUtil.java:195)
    at com.intellij.codeInspection.SuppressManagerImpl.getSuppressedInspectionIdsIn(SuppressManagerImpl.java:83)
    at com.intellij.codeInspection.ex.JavaInspectionExtensionsFactory.getSuppressedInspectionIdsIn(JavaInspectionExtensionsFactory.java:62)
    at com.intellij.codeInspection.ex.EditInspectionToolsSettingsInSuppressedPlaceIntention.getSuppressedId(EditInspectionToolsSettingsInSuppressedPlaceIntention.java:61)
    at com.intellij.codeInspection.ex.EditInspectionToolsSettingsInSuppressedPlaceIntention.isAvailable(EditInspectionToolsSettingsInSuppressedPlaceIntention.java:82)
    at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:132)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$2(ShowIntentionsPass.java:298)
    at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:157)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:297)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getIntentionActionsToShow(ShowIntentionsPass.java:222)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:198)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$0(PassExecutorService.java:432)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1033)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:425)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:424)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:400)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

```
org.jf.smalidea.psi.impl.SmaliMethod.getStubOrPsiParent()Lcom/intellij/psi/PsiElement;
```

**Comment by JesusFreke** [comment] 2016-10-23 18:31
Duplicate of #54

**Closed as completed by JesusFreke** 2016-10-23 18:31 UTC
