### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#13] opened 2016-06-09 22:44 UTC
protocol.version: 1
os.name: Windows 7
java.version: 1.8.0_77
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IC-145.1617
app.version.major: 2016
app.version.minor: 1.3
app.build.date: 1464908400000
app.build.date.release: 1464908400000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.03
last.action: null
previous.exception: null
assignee.id: null

```
java.lang.AssertionError
    at org.jf.smalidea.debugging.value.LazyValue.getValue(LazyValue.java:128)
    at org.jf.smalidea.debugging.value.LazyObjectReference.enableCollection(LazyObjectReference.java:75)
    at com.intellij.debugger.impl.DebuggerUtilsEx.enableCollection(DebuggerUtilsEx.java:954)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at com.intellij.debugger.engine.SuspendContextImpl.resume(SuspendContextImpl.java:94)
    at com.intellij.debugger.engine.SuspendManagerImpl.resume(SuspendManagerImpl.java:189)
    at com.intellij.debugger.engine.DebugProcessImpl$ResumeCommand.resumeAction(DebugProcessImpl.java:1732)
    at com.intellij.debugger.engine.DebugProcessImpl$StepCommand.resumeAction(DebugProcessImpl.java:1705)
    at com.intellij.debugger.engine.DebugProcessImpl$ResumeCommand.contextAction(DebugProcessImpl.java:1727)
    at com.intellij.debugger.engine.DebugProcessImpl$StepOverCommand.contextAction(DebugProcessImpl.java:1632)
    at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:61)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:153)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```

```
null
```

**Comment by JesusFreke** [comment] 2016-07-24 21:49
Duplicate of #4

**Closed as completed by JesusFreke** 2016-07-24 21:49 UTC
