### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#26] opened 2016-07-16 05:23 UTC
protocol.version: 1
os.name: Windows 10
java.version: 1.8.0_76-release
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-162.1121.32
app.version.major: 2016
app.version.minor: 2
app.build.date: 1467993600000
app.build.date.release: 1468252800000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.03
last.action: 
previous.exception: null
assignee.id: null

```
java.lang.NoSuchMethodError: org.jf.smalidea.psi.impl.SmaliImplementsList.getStubOrPsiParent()Lcom/intellij/psi/PsiElement;
    at org.jf.smalidea.psi.impl.SmaliImplementsList.getImplementsElements(SmaliImplementsList.java:59)
    at org.jf.smalidea.psi.impl.SmaliImplementsList.getReferenceElements(SmaliImplementsList.java:53)
    at org.jf.smalidea.psi.impl.SmaliBaseReferenceList.getSmaliNames(SmaliBaseReferenceList.java:99)
    at org.jf.smalidea.psi.stub.element.SmaliImplementsListElementType.createStub(SmaliImplementsListElementType.java:65)
    at org.jf.smalidea.psi.stub.element.SmaliImplementsListElementType.createStub(SmaliImplementsListElementType.java:40)
    at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:74)
    at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:36)
    at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:86)
    at com.intellij.psi.stubs.StubTreeLoaderImpl.a(StubTreeLoaderImpl.java:61)
    at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
    at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
    at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:61)
    at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:714)
    at com.intellij.psi.impl.source.PsiFileImpl.getStub(PsiFileImpl.java:694)
    at org.jf.smalidea.psi.impl.SmaliFile.getPsiClass(SmaliFile.java:57)
    at org.jf.smalidea.psi.impl.SmaliFile.getClasses(SmaliFile.java:71)
    at org.jf.smalidea.psi.impl.SmaliFile.getClasses(SmaliFile.java:46)
    at com.intellij.ide.projectView.impl.ClassesTreeStructureProvider$1.compute(ClassesTreeStructureProvider.java:81)
    at com.intellij.ide.projectView.impl.ClassesTreeStructureProvider$1.compute(ClassesTreeStructureProvider.java:77)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:866)
    at com.intellij.ide.projectView.impl.ClassesTreeStructureProvider.modify(ClassesTreeStructureProvider.java:77)
    at com.intellij.ide.util.treeView.AbstractTreeStructureBase.getChildElements(AbstractTreeStructureBase.java:53)
    at com.intellij.ide.util.treeView.AbstractTreeUi$31.perform(AbstractTreeUi.java:1614)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1832)
    at com.intellij.ide.util.treeView.AbstractTreeUi.getChildrenFor(AbstractTreeUi.java:1611)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$4500(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$30.perform(AbstractTreeUi.java:1536)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1832)
    at com.intellij.ide.util.treeView.AbstractTreeUi.processUnbuilt(AbstractTreeUi.java:1523)
    at com.intellij.ide.util.treeView.AbstractTreeUi.doUpdateChildren(AbstractTreeUi.java:1246)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$2900(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$25$1.perform(AbstractTreeUi.java:1169)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1832)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$2500(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$25.perform(AbstractTreeUi.java:1166)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildren(AbstractTreeUi.java:1161)
    at com.intellij.ide.util.treeView.AbstractTreeUi.updateSubtreeNow(AbstractTreeUi.java:1070)
    at com.intellij.ide.util.treeView.AbstractTreeUpdater$3.perform(AbstractTreeUpdater.java:258)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.AbstractTreeUpdater.performUpdate(AbstractTreeUpdater.java:254)
    at com.intellij.ide.util.treeView.AbstractTreeUi$13.perform(AbstractTreeUi.java:500)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:187)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.AbstractTreeUi.doExpandNodeChildren(AbstractTreeUi.java:496)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder.expandNodeChildren(AbstractTreeBuilder.java:347)
    at com.intellij.ide.projectView.BaseProjectTreeBuilder.expandNodeChildren(BaseProjectTreeBuilder.java:108)
    at com.intellij.ide.util.treeView.AbstractTreeUi$MyExpansionListener.treeExpanded(AbstractTreeUi.java:4803)
    at javax.swing.JTree.fireTreeExpanded(JTree.java:2775)
    at javax.swing.JTree.setExpandedState(JTree.java:3629)
    at javax.swing.JTree.expandPath(JTree.java:2212)
    at com.intellij.ide.util.treeView.AbstractTreeUi$52.perform(AbstractTreeUi.java:3259)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.ide.util.treeView.UpdaterTreeState.process(UpdaterTreeState.java:123)
    at com.intellij.ide.util.treeView.AbstractTreeUi.processInnerChange(AbstractTreeUi.java:3280)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expandPath(AbstractTreeUi.java:3248)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:1503)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:1470)
    at com.intellij.ide.util.treeView.AbstractTreeUi.processExpand(AbstractTreeUi.java:4463)
    at com.intellij.ide.util.treeView.AbstractTreeUi._expand(AbstractTreeUi.java:4399)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$8300(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$73.perform(AbstractTreeUi.java:4277)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expandNext(AbstractTreeUi.java:4291)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$8400(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$72.perform(AbstractTreeUi.java:4237)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1832)
    at com.intellij.ide.util.treeView.AbstractTreeUi.runDone(AbstractTreeUi.java:4324)
    at com.intellij.ide.util.treeView.AbstractTreeUi._expand(AbstractTreeUi.java:4211)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:4201)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:4196)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expand(AbstractTreeUi.java:4192)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder.expand(AbstractTreeBuilder.java:127)
    at com.intellij.ide.util.treeView.TreeState$BuilderFacade.expand(TreeState.java:486)
    at com.intellij.ide.util.treeView.TreeState.applyTo(TreeState.java:372)
    at com.intellij.ide.util.treeView.TreeState.access$500(TreeState.java:45)
    at com.intellij.ide.util.treeView.TreeState$3.perform(TreeState.java:383)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.TreeState.applyTo(TreeState.java:372)
    at com.intellij.ide.util.treeView.TreeState.access$500(TreeState.java:45)
    at com.intellij.ide.util.treeView.TreeState$3.perform(TreeState.java:383)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.TreeState.applyTo(TreeState.java:372)
    at com.intellij.ide.util.treeView.TreeState.access$500(TreeState.java:45)
    at com.intellij.ide.util.treeView.TreeState$3.perform(TreeState.java:383)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.TreeState.applyTo(TreeState.java:372)
    at com.intellij.ide.util.treeView.TreeState.access$500(TreeState.java:45)
    at com.intellij.ide.util.treeView.TreeState$3.perform(TreeState.java:383)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.openapi.util.ExecutionCallback.doWhenExecuted(ExecutionCallback.java:100)
    at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
    at com.intellij.ide.util.treeView.TreeState.applyTo(TreeState.java:372)
    at com.intellij.ide.util.treeView.TreeState.access$500(TreeState.java:45)
    at com.intellij.ide.util.treeView.TreeState$3.perform(TreeState.java:383)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:58)
    at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:72)
    at com.intellij.openapi.util.ActionCallback$3.run(ActionCallback.java:275)
    at com.intellij.ide.util.treeView.AbstractTreeUi.executeUserRunnable(AbstractTreeUi.java:2536)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder$UserRunnable.run(AbstractTreeBuilder.java:679)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1832)
    at com.intellij.ide.util.treeView.AbstractTreeUi.runDone(AbstractTreeUi.java:4324)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$5000(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$72$2.perform(AbstractTreeUi.java:4228)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:58)
    at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:72)
    at com.intellij.ide.util.treeView.AbstractTreeUi$73$1.perform(AbstractTreeUi.java:4280)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1832)
    at com.intellij.ide.util.treeView.AbstractTreeUi.runDone(AbstractTreeUi.java:4324)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$5000(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$76.onReady(AbstractTreeUi.java:4438)
    at com.intellij.ide.util.treeView.AbstractTreeUi.processActions(AbstractTreeUi.java:2867)
    at com.intellij.ide.util.treeView.AbstractTreeUi.processNodeActionsIfReady(AbstractTreeUi.java:2834)
    at com.intellij.ide.util.treeView.AbstractTreeUi.processExpand(AbstractTreeUi.java:4467)
    at com.intellij.ide.util.treeView.AbstractTreeUi._expand(AbstractTreeUi.java:4399)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$8300(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$73.perform(AbstractTreeUi.java:4277)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.ide.util.treeView.AbstractTreeUi.expandNext(AbstractTreeUi.java:4291)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$8400(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$72.perform(AbstractTreeUi.java:4237)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.ide.util.treeView.AbstractTreeUi.flushPendingNodeActions(AbstractTreeUi.java:2168)
    at com.intellij.ide.util.treeView.AbstractTreeUi.maybeYeildingFinished(AbstractTreeUi.java:2097)
    at com.intellij.ide.util.treeView.AbstractTreeUi.executeYieldingRequest(AbstractTreeUi.java:2085)
    at com.intellij.ide.util.treeView.AbstractTreeUi.access$5700(AbstractTreeUi.java:66)
    at com.intellij.ide.util.treeView.AbstractTreeUi$36$1.perform(AbstractTreeUi.java:1978)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder.runOnYeildingDone(AbstractTreeBuilder.java:425)
    at com.intellij.ide.util.treeView.AbstractTreeUi.runOnYieldingDone(AbstractTreeUi.java:2176)
    at com.intellij.ide.util.treeView.AbstractTreeUi$36.perform(AbstractTreeUi.java:1973)
    at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
    at com.intellij.ide.util.treeView.AbstractTreeBuilder.lambda$new$0(AbstractTreeBuilder.java:51)
    at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:99)
    at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
    at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:58)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:863)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

```
org.jf.smalidea.psi.impl.SmaliImplementsList.getStubOrPsiParent()Lcom/intellij/psi/PsiElement;
```

**Comment by JesusFreke** [comment] 2016-10-23 18:11
Duplicate of #16

**Closed as completed by JesusFreke** 2016-10-23 18:11 UTC
