### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#74] opened 2016-09-12 04:20 UTC
protocol.version: 1
os.name: Windows 7
java.version: 1.8.0_101
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-162.2032.8
app.version.major: 2016
app.version.minor: 2.4
app.build.date: 1473350400000
app.build.date.release: 1468252800000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.03
last.action: AndroidConnectDebuggerAction
previous.exception: null
assignee.id: null

```
java.lang.NoSuchMethodError: org.jf.smalidea.psi.impl.SmaliMethod.getStubOrPsiParent()Lcom/intellij/psi/PsiElement;
    at org.jf.smalidea.psi.impl.SmaliMethod.getContainingClass(SmaliMethod.java:262)
    at org.jf.smalidea.psi.impl.SmaliMethod.getContainingClass(SmaliMethod.java:66)
    at com.intellij.codeInsight.intention.impl.ImplementAbstractMethodAction.isAvailable(ImplementAbstractMethodAction.java:58)
    at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.isAvailable(IntentionActionWrapper.java:56)
    at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:132)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.a(ShowIntentionsPass.java:298)
    at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:157)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:297)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.a(ShowIntentionsPass.java:222)
    at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:198)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:434)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1026)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:427)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:426)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
    at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
    at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
    at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

```

```
org.jf.smalidea.psi.impl.SmaliMethod.getStubOrPsiParent()Lcom/intellij/psi/PsiElement;
```

**Comment by JesusFreke** [comment] 2016-10-23 18:31
Duplicate of #54

**Closed as completed by JesusFreke** 2016-10-23 18:31 UTC
