### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#206] opened 2017-02-22 08:00 UTC
protocol.version: 1
os.name: Mac OS X
java.version: 1.8.0_112-release
java.vm.vendor: JetBrains s.r.o
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-163.12024.16
app.version.major: 2016
app.version.minor: 3.4
app.build.date: 1485857100902
app.build.date.release: 1479772800902
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.03
last.action: null
previous.exception: null
assignee.id: null

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'project' of com/intellij/psi/stubs/AbstractStubIndex.get must not be null
	at com.intellij.psi.stubs.AbstractStubIndex.get(AbstractStubIndex.java)
	at org.jf.smalidea.psi.index.SmaliClassFinder.findClass(SmaliClassFinder.java:45)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:122)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:99)
	at com.intellij.codeInsight.MetaAnnotationUtil.getAnnotationTypesWithChildren(MetaAnnotationUtil.java:112)
	at com.intellij.codeInsight.MetaAnnotationUtil.lambda$null$0(MetaAnnotationUtil.java:61)
	at com.intellij.util.containers.ConcurrentFactoryMap$1.create(ConcurrentFactoryMap.java:40)
	at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:57)
	at com.intellij.codeInsight.MetaAnnotationUtil.getAnnotationTypesWithChildren(MetaAnnotationUtil.java:66)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl.getAnnotationTypes(JamAnnotationTypeUtilImpl.java:137)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl.getAnnotationTypesWithChildren(JamAnnotationTypeUtilImpl.java:126)
	at com.intellij.spring.model.jam.stereotype.SpringMetaStereotypeComponent.getAnnotations(SpringMetaStereotypeComponent.java:65)
	at com.intellij.spring.model.jam.stereotype.SpringConfiguration.lambda$static$0(SpringConfiguration.java:53)
	at com.intellij.spring.model.jam.SpringSemContributorUtil.lambda$createFunction$1(SpringSemContributorUtil.java:90)
	at com.intellij.semantic.SemServiceImpl$2.a(SemServiceImpl.java:92)
	at com.intellij.semantic.SemServiceImpl.a(SemServiceImpl.java:177)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:148)
	at com.intellij.semantic.SemService.getSemElement(SemService.java:37)
	at com.intellij.spring.model.jam.SpringSemContributorUtil.lambda$registerMetaComponents$0(SpringSemContributorUtil.java:72)
	at com.intellij.semantic.SemServiceImpl$2.a(SemServiceImpl.java:92)
	at com.intellij.semantic.SemServiceImpl.a(SemServiceImpl.java:177)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:148)
	at com.intellij.semantic.SemService.getSemElement(SemService.java:37)
	at com.intellij.jam.JamService.getJamElement(JamService.java:119)
	at com.intellij.spring.model.utils.SpringCommonUtils.isConfigurationOrMeta(SpringCommonUtils.java:139)
	at com.intellij.spring.model.highlighting.SpringAutowiredFieldsWarningInspection.checkClass(SpringAutowiredFieldsWarningInspection.java:41)
	at com.intellij.codeInspection.AbstractBaseJavaLocalInspectionTool$1.visitClass(AbstractBaseJavaLocalInspectionTool.java:94)
	at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:473)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:280)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:249)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:123)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1061)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

```
Argument for @NotNull parameter 'project' of com/intellij/psi/stubs/AbstractStubIndex.get must not be null
```

**Comment by JesusFreke** [comment] 2017-03-11 20:44
Duplicate of #137

**Closed as completed by JesusFreke** 2017-03-11 20:44 UTC
