### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#160] opened 2017-01-07 16:13 UTC
protocol.version: 1
os.name: Windows 7
java.version: 1.8.0_25
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IC-139.1117
app.version.major: 14
app.version.minor: 0.3
app.build.date: 1421769600000
app.build.date.release: 1421769600000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.03
last.action: StepOver
previous.exception: null
assignee.id: null

```
java.lang.NullPointerException
	at com.sun.tools.jdi.LocalVariableImpl.isVisible(LocalVariableImpl.java:135)
	at com.sun.tools.jdi.StackFrameImpl.getValues(StackFrameImpl.java:214)
	at com.sun.tools.jdi.StackFrameImpl.getValue(StackFrameImpl.java:201)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.evaluateRegister(SmaliCodeFragmentFactory.java:316)
	at org.jf.smalidea.debugging.value.LazyValue.getNullableValue(LazyValue.java:116)
	at org.jf.smalidea.debugging.value.LazyValue.getValue(LazyValue.java:127)
	at org.jf.smalidea.debugging.value.LazyObjectReference.isCollected(LazyObjectReference.java:79)
	at com.intellij.debugger.jdi.VirtualMachineProxyImpl.isCollected(VirtualMachineProxyImpl.java:636)
	at com.intellij.debugger.ui.impl.watch.EvaluationDescriptor.calcValue(EvaluationDescriptor.java:130)
	at com.intellij.debugger.ui.impl.watch.ValueDescriptorImpl.setContext(ValueDescriptorImpl.java:188)
	at com.intellij.debugger.engine.JavaDebuggerEvaluator$1.threadAction(JavaDebuggerEvaluator.java:87)
	at com.intellij.debugger.engine.events.DebuggerContextCommandImpl.contextAction(DebuggerContextCommandImpl.java:59)
	at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:61)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:151)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:39)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:146)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:28)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:55)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

```

```
null
```

**Comment by JesusFreke** [comment] 2017-03-11 20:48
Duplicate of #9

**Closed as completed by JesusFreke** 2017-03-11 20:48 UTC
