### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#103] opened 2016-10-22 05:49 UTC
protocol.version: 1
os.name: Windows 7
java.version: 1.8.0_101
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IC-162.2032.8
app.version.major: 2016
app.version.minor: 2.4
app.build.date: 1473350400000
app.build.date.release: 1473350400000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 162.2228.15
plugin.name: Smalidea
plugin.version: 0.03
last.action: ToggleLineBreakpoint
previous.exception: null
assignee.id: null

```
java.lang.NoSuchMethodError: org.jf.smalidea.psi.impl.SmaliMethod.getStubOrPsiParent()Lcom/intellij/psi/PsiElement;
    at org.jf.smalidea.psi.impl.SmaliMethod.getContainingClass(SmaliMethod.java:262)
    at org.jf.smalidea.psi.impl.SmaliMethod.getContainingClass(SmaliMethod.java:66)
    at com.intellij.debugger.engine.JVMNameUtil.getJVMSignature(JVMNameUtil.java:327)
    at com.intellij.debugger.ui.breakpoints.MethodBreakpoint$1.compute(MethodBreakpoint.java:329)
    at com.intellij.debugger.ui.breakpoints.MethodBreakpoint$1.compute(MethodBreakpoint.java:307)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:859)
    at com.intellij.debugger.ui.breakpoints.MethodBreakpoint.getMethodDescriptor(MethodBreakpoint.java:307)
    at com.intellij.debugger.ui.breakpoints.MethodBreakpoint.reload(MethodBreakpoint.java:111)
    at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.reload(BreakpointWithHighlighter.java:242)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:843)
    at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.<init>(BreakpointWithHighlighter.java:178)
    at com.intellij.debugger.ui.breakpoints.MethodBreakpoint.<init>(MethodBreakpoint.java:76)
    at com.intellij.debugger.ui.breakpoints.JavaMethodBreakpointType.createJavaBreakpoint(JavaMethodBreakpointType.java:129)
    at com.intellij.debugger.ui.breakpoints.BreakpointManager.getJavaBreakpoint(BreakpointManager.java:513)
    at com.intellij.debugger.ui.breakpoints.BreakpointManager$2.breakpointAdded(BreakpointManager.java:129)
    at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
    at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
    at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
    at com.sun.proxy.$Proxy67.breakpointAdded(Unknown Source)
    at com.intellij.xdebugger.impl.breakpoints.XBreakpointManagerImpl.addBreakpoint(XBreakpointManagerImpl.java:149)
    at com.intellij.xdebugger.impl.breakpoints.XBreakpointManagerImpl.addLineBreakpoint(XBreakpointManagerImpl.java:225)
    at com.intellij.xdebugger.impl.XDebuggerUtilImpl$1.run(XDebuggerUtilImpl.java:269)
    at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
    at com.intellij.openapi.application.WriteAction.execute(WriteAction.java:39)
    at com.intellij.xdebugger.impl.XDebuggerUtilImpl.toggleAndReturnLineBreakpoint(XDebuggerUtilImpl.java:274)
    at com.intellij.xdebugger.impl.breakpoints.XBreakpointUtil.toggleLineBreakpoint(XBreakpointUtil.java:175)
    at com.intellij.xdebugger.impl.breakpoints.XLineBreakpointManager$MyEditorMouseListener.mouseClicked(XLineBreakpointManager.java:285)
    at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
    at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
    at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
    at com.sun.proxy.$Proxy24.mouseClicked(Unknown Source)
    at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMouseClickedCommand(EditorImpl.java:5829)
    at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:5756)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
    at java.awt.Component.processMouseEvent(Component.java:6533)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6298)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:793)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:625)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

```
org.jf.smalidea.psi.impl.SmaliMethod.getStubOrPsiParent()Lcom/intellij/psi/PsiElement;
```

**Comment by JesusFreke** [comment] 2016-10-23 18:31
Duplicate of #54

**Closed as completed by JesusFreke** 2016-10-23 18:31 UTC
