### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#21] opened 2016-07-03 09:21 UTC
protocol.version: 1
os.name: Linux
java.version: 1.8.0_76-release
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-145.597
app.version.major: 2016
app.version.minor: 1.1
app.build.date: 1459180800000
app.build.date.release: 1458057600000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.03
last.action: null
previous.exception: null
assignee.id: null

```
java.lang.AssertionError
    at org.jf.smalidea.util.NameUtils.javaToSmaliType(NameUtils.java:77)
    at org.jf.smalidea.findUsages.SmaliClassReferenceSearcher$1.compute(SmaliClassReferenceSearcher.java:63)
    at org.jf.smalidea.findUsages.SmaliClassReferenceSearcher$1.compute(SmaliClassReferenceSearcher.java:59)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:962)
    at org.jf.smalidea.findUsages.SmaliClassReferenceSearcher.processQuery(SmaliClassReferenceSearcher.java:58)
    at org.jf.smalidea.findUsages.SmaliClassReferenceSearcher.processQuery(SmaliClassReferenceSearcher.java:51)
    at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:79)
    at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
    at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
    at com.intellij.util.MergeQuery.processSubQuery(MergeQuery.java:84)
    at com.intellij.util.MergeQuery.forEach(MergeQuery.java:56)
    at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
    at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
    at com.intellij.util.UniqueResultsQuery.findAll(UniqueResultsQuery.java:78)
    at com.intellij.find.findUsages.FindUsagesHandler.findReferencesToHighlight(FindUsagesHandler.java:174)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.a(IdentifierHighlighterPass.java:156)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getHighlightUsages(IdentifierHighlighterPass.java:133)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.a(IdentifierHighlighterPass.java:189)
    at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:106)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)

```

```
null
```

**Comment by JesusFreke** [comment] 2016-10-23 18:15
Duplicate of #4

**Closed as completed by JesusFreke** 2016-10-23 18:15 UTC
