### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#156] opened 2017-01-05 05:07 UTC
protocol.version: 1
os.name: Windows 7
java.version: 1.8.0_77
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IC-145.2070
app.version.major: 2016
app.version.minor: 1.4
app.build.date: 1470067200000
app.build.date.release: 1470067200000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.03
last.action: null
previous.exception: null
assignee.id: null

```
org.jf.dexlib2.analysis.UnresolvedClassException: Could not resolve class Ljava/io/InterruptedIOException;
	at org.jf.dexlib2.analysis.ClassPath.getClassDef(ClassPath.java:155)
	at org.jf.dexlib2.analysis.ClassProto$1.get(ClassProto.java:94)
	at org.jf.dexlib2.analysis.ClassProto$1.get(ClassProto.java:92)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
	at org.jf.dexlib2.analysis.ClassProto.getClassDef(ClassProto.java:88)
	at org.jf.dexlib2.analysis.ClassProto.isInterface(ClassProto.java:106)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstanceOf(MethodAnalyzer.java:1184)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:649)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:206)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:141)
	at org.jf.smalidea.psi.impl.SmaliMethod.getMethodAnalyzer(SmaliMethod.java:327)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstructionFromMethod(SmaliInstruction.java:199)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstruction(SmaliInstruction.java:222)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.wrapContext(SmaliCodeFragmentFactory.java:137)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.createPresentationCodeFragment(SmaliCodeFragmentFactory.java:93)
	at com.intellij.debugger.engine.evaluation.CodeFragmentFactoryContextWrapper.createPresentationCodeFragment(CodeFragmentFactoryContextWrapper.java:61)
	at org.jetbrains.java.debugger.JavaDebuggerEditorsProvider.createExpressionCodeFragment(JavaDebuggerEditorsProvider.java:88)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:45)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.createDocument(XDebuggerEditorBase.java:244)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionComboBox$1.setItem(XDebuggerExpressionComboBox.java:102)
	at com.intellij.openapi.ui.ComboBox$MyEditor.setItem(ComboBox.java:376)
	at javax.swing.JComboBox.configureEditor(JComboBox.java:1404)
	at javax.swing.plaf.basic.BasicComboBoxUI.configureEditor(BasicComboBoxUI.java:800)
	at javax.swing.plaf.basic.BasicComboBoxUI.addEditor(BasicComboBoxUI.java:749)
	at javax.swing.plaf.basic.BasicComboBoxUI$Handler.propertyChange(BasicComboBoxUI.java:1724)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8430)
	at javax.swing.JComboBox.setEditor(JComboBox.java:506)
	at com.intellij.openapi.ui.ComboBox.setEditor(ComboBox.java:259)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionComboBox.initEditor(XDebuggerExpressionComboBox.java:112)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionComboBox.<init>(XDebuggerExpressionComboBox.java:57)
	at com.intellij.xdebugger.impl.ui.tree.XDebuggerTreeInplaceEditor.<init>(XDebuggerTreeInplaceEditor.java:40)
	at com.intellij.xdebugger.impl.frame.WatchInplaceEditor.<init>(WatchInplaceEditor.java:46)
	at com.intellij.xdebugger.impl.ui.tree.nodes.WatchesRootNode.editWatch(WatchesRootNode.java:216)
	at com.intellij.xdebugger.impl.ui.tree.nodes.WatchesRootNode.addNewWatch(WatchesRootNode.java:201)
	at com.intellij.xdebugger.impl.frame.actions.XNewWatchAction.perform(XNewWatchAction.java:34)
	at com.intellij.xdebugger.impl.frame.actions.XWatchesTreeActionBase.actionPerformed(XWatchesTreeActionBase.java:60)
	at com.intellij.xdebugger.impl.frame.XWatchesViewImpl.executeAction(XWatchesViewImpl.java:279)
	at com.intellij.xdebugger.impl.frame.XWatchesViewImpl.access$000(XWatchesViewImpl.java:73)
	at com.intellij.xdebugger.impl.frame.XWatchesViewImpl$2.run(XWatchesViewImpl.java:121)
	at com.intellij.xdebugger.impl.frame.XWatchesViewImpl$2.run(XWatchesViewImpl.java:118)
	at com.intellij.ui.ToolbarDecorator$3.doAdd(ToolbarDecorator.java:434)
	at com.intellij.ui.CommonActionsPanel$Buttons.performAction(CommonActionsPanel.java:71)
	at com.intellij.ui.CommonActionsPanel$MyActionButton.actionPerformed(CommonActionsPanel.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:191)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:162)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:126)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:300)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


```

```
Could not resolve class Ljava/io/InterruptedIOException;
```

**Comment by JesusFreke** [comment] 2017-03-11 20:46
Duplicate of #5

**Closed as completed by JesusFreke** 2017-03-11 20:46 UTC
