### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#177] opened 2017-01-12 13:50 UTC
protocol.version: 1
os.name: Mac OS X
java.version: 1.8.0_112-release
java.vm.vendor: JetBrains s.r.o
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: true
app.internal: false
app.build: IU-171.2014.21
app.version.major: 2017
app.version.minor: 1
app.build.date: 1483014242285
app.build.date.release: 1488844802285
app.compilation.timestamp: null
update.channel.status: eap
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.03
last.action: null
previous.exception: null
assignee.id: null

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'project' of com/intellij/psi/stubs/AbstractStubIndex.get must not be null
	at com.intellij.psi.stubs.AbstractStubIndex.get(AbstractStubIndex.java)
	at org.jf.smalidea.psi.index.SmaliClassFinder.findClass(SmaliClassFinder.java:45)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:131)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:108)
	at com.intellij.codeInsight.MetaAnnotationUtil.getAnnotationTypesWithChildren(MetaAnnotationUtil.java:112)
	at com.intellij.codeInsight.MetaAnnotationUtil.lambda$null$0(MetaAnnotationUtil.java:61)
	at com.intellij.util.containers.ConcurrentFactoryMap$1.create(ConcurrentFactoryMap.java:40)
	at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:57)
	at com.intellij.codeInsight.MetaAnnotationUtil.getAnnotationTypesWithChildren(MetaAnnotationUtil.java:66)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl.getAnnotationTypes(JamAnnotationTypeUtilImpl.java:137)
	at com.intellij.spring.model.jam.utils.JamAnnotationTypeUtilImpl.getAnnotationTypesWithChildren(JamAnnotationTypeUtilImpl.java:126)
	at com.intellij.spring.model.jam.SpringSemContributorUtil$2.getAnnotationTypes(SpringSemContributorUtil.java:197)
	at com.intellij.spring.model.jam.SpringSemContributorUtil$2.fun(SpringSemContributorUtil.java:158)
	at com.intellij.spring.model.jam.SpringSemContributorUtil$2.fun(SpringSemContributorUtil.java:152)
	at com.intellij.spring.model.jam.SpringSemContributorUtil.lambda$createFunction$1(SpringSemContributorUtil.java:90)
	at com.intellij.semantic.SemServiceImpl$2.a(SemServiceImpl.java:92)
	at com.intellij.semantic.SemServiceImpl.a(SemServiceImpl.java:177)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:148)
	at com.intellij.semantic.SemService.getSemElement(SemService.java:37)
	at com.intellij.spring.model.jam.SpringSemContributorUtil.lambda$registerMetaComponents$0(SpringSemContributorUtil.java:72)
	at com.intellij.semantic.SemServiceImpl$2.a(SemServiceImpl.java:92)
	at com.intellij.semantic.SemServiceImpl.a(SemServiceImpl.java:177)
	at com.intellij.semantic.SemServiceImpl.getSemElements(SemServiceImpl.java:148)
	at com.intellij.semantic.SemService.getSemElement(SemService.java:37)
	at com.intellij.jam.JamService.getJamElement(JamService.java:119)
	at com.intellij.spring.web.mvc.SpringControllerClassInfo.hasRequestMappingJam(SpringControllerClassInfo.java:147)
	at com.intellij.spring.web.mvc.SpringControllerClassInfo.isJamRequestHandler(SpringControllerClassInfo.java:143)
	at com.intellij.spring.web.mvc.code.SpringMVCImplicitUsageProvider.isAnnotated(SpringMVCImplicitUsageProvider.java:54)
	at com.intellij.spring.web.mvc.code.SpringMVCImplicitUsageProvider.isImplicitWrite(SpringMVCImplicitUsageProvider.java:39)
	at com.intellij.spring.web.mvc.code.SpringMVCImplicitUsageProvider.isImplicitUsage(SpringMVCImplicitUsageProvider.java:28)
	at com.intellij.codeInsight.daemon.impl.UnusedSymbolUtil.isImplicitUsage(UnusedSymbolUtil.java:55)
	at com.intellij.codeInsight.daemon.impl.UnusedSymbolUtil.isMethodReferenced(UnusedSymbolUtil.java:147)
	at com.intellij.codeInsight.daemon.impl.analysis.PostHighlightingVisitor.a(PostHighlightingVisitor.java:427)
	at com.intellij.codeInsight.daemon.impl.analysis.PostHighlightingVisitor.a(PostHighlightingVisitor.java:233)
	at com.intellij.codeInsight.daemon.impl.analysis.PostHighlightingVisitor.collectHighlights(PostHighlightingVisitor.java:160)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.a(HighlightVisitorImpl.java:175)
	at com.intellij.codeInsight.daemon.impl.analysis.RefCountHolder.analyze(RefCountHolder.java:335)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:171)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:329)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:329)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:86)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:329)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:297)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:237)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1129)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:433)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:587)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:408)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:238)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:406)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

```
Argument for @NotNull parameter 'project' of com/intellij/psi/stubs/AbstractStubIndex.get must not be null
```

**Comment by JesusFreke** [comment] 2017-03-11 20:44
Duplicate of #137

**Closed as completed by JesusFreke** 2017-03-11 20:44 UTC
