### ISSUE TITLE
[auto-generated] Crash in plugin

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [SmalideaIssueReporter/smalidea-issues#14] opened 2016-06-10 18:11 UTC
protocol.version: 1
os.name: Linux
java.version: 1.7.0_101
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IC-143.2370
app.version.major: 15
app.version.minor: 0.6
app.build.date: 1461816000000
app.build.date.release: 1461816000000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 145.258
plugin.name: Smalidea
plugin.version: 0.03
last.action: EditorBackSpace
previous.exception: null
assignee.id: null

```
java.lang.AssertionError
    at org.jf.smalidea.debugging.value.LazyValue.getValue(LazyValue.java:128)
    at org.jf.smalidea.debugging.value.LazyValue.type(LazyValue.java:134)
    at com.intellij.debugger.codeinsight.RuntimeTypeEvaluator.getCastableRuntimeType(RuntimeTypeEvaluator.java:87)
    at com.intellij.debugger.codeinsight.RuntimeTypeEvaluator.evaluate(RuntimeTypeEvaluator.java:79)
    at com.intellij.debugger.codeinsight.RuntimeTypeEvaluator.evaluate(RuntimeTypeEvaluator.java:46)
    at com.intellij.debugger.ui.EditorEvaluationCommand.evaluate(EditorEvaluationCommand.java:69)
    at com.intellij.debugger.codeinsight.RuntimeTypeEvaluator.threadAction(RuntimeTypeEvaluator.java:54)
    at com.intellij.debugger.engine.events.DebuggerContextCommandImpl.contextAction(DebuggerContextCommandImpl.java:89)
    at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:61)
    at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:153)
    at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
    at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
    at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
    at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

```

```
null
```

**Comment by JesusFreke** [comment] 2016-10-23 18:15
Duplicate of #4

**Closed as completed by JesusFreke** 2016-10-23 18:15 UTC
